service: api-usuarios-chinawok
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  stage: prod
  environment:
    AWS_REGION: us-east-1
    TABLE_USUARIOS: ChinaWok-Usuarios
    TABLE_TOKENS: ChinaWok-Tokens
    TOKEN_FUNCTION_NAME: Validar_Token_Acceso_ChinaWok

functions:
  crear:
    handler: crear_usuario.lambda_handler
    events:
      - http:
          path: usuario/crear
          method: post
          cors: true

  login:
    handler: login.lambda_handler
    events:
      - http:
          path: usuario/login
          method: post
          cors: true

  listar:
    handler: listar_usuarios.lambda_handler
    events:
      - http:
          path: usuario/listar
          method: get
          cors: true

  buscar:
    handler: buscar_usuario.lambda_handler
    events:
      - http:
          path: usuario/buscar
          method: post
          cors: true

  modificar:
    handler: modificar_usuario.lambda_handler
    events:
      - http:
          path: usuario/modificar
          method: put
          cors: true

  eliminar:
    handler: eliminar_usuario.lambda_handler
    events:
      - http:
          path: usuario/eliminar
          method: delete
          cors: true

  validarToken:
    handler: validar_token.lambda_handler
    events:
      - http:
          path: usuario/validartoken
          method: post
          cors: true
